name: waterflyiii
description: Waterfly III, a mobile client for Firefly III
publish_to: "none"

version: 1.2.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: 2.11.0
  intl: 0.19.0
  path_provider: ^2.1.4
  collection: ^1.18.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  chopper: ^8.0.2
  json_annotation: ^4.8.0
  flutter_svg: ^2.1.0
  url_launcher: ^6.2.4
  infinite_scroll_pagination: ^5.0.0
  badges: ^3.1.2
  filesize: ^2.0.1
  community_charts_flutter: ^1.0.2
  file_picker: ^8.1.0
  animations: ^2.0.11
  flutter_local_notifications: ^19.2.1
  notifications_listener_service:
    git:
      url: https://github.com/dreautall/notification_listener_service.git
      ref: main
  appcheck:
    git:
      url: https://github.com/bugrevealingbme/AppCheck.git
      ref: ce371398f86412a8d9a2e0b75a9b51597ea1d79f
  package_info_plus: ^8.2.0
  logging: ^1.1.1
  flutter_email_sender: ^7.0.0
  local_auth: ^2.1.8
  dynamic_color: ^1.7.0
  material_color_utilities: ^0.8.0
  version: ^3.0.2
  quick_actions: ^1.0.7
  stock: ^1.1.0
  syncfusion_flutter_charts: ^26.2.4
  image_picker: ^1.0.7
  timezone: ^0.10.0
  flutter_timezone: ^4.1.1
  flutter_sharing_intent: ^1.1.1
  http: ^1.2.1
  open_file_plus:
    git:
      url: https://github.com/postflow/open_file_plus.git
      ref: main
  cronet_http: ^1.3.0
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_lints: ^4.0.0
  # needed for swagger_dart_code_generator
  build_runner: ^2.4.11
  chopper_generator: ^8.0.3
  json_serializable: ^6.8.0
  swagger_dart_code_generator: ^3.0.1
  flutter_native_splash: ^2.3.0
  translations_cleaner: ^0.0.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/logo.svg

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#fdfcfe"
  color_dark: "#1a1c1e"
